const FORM_SUBMISSION_STATUS = "FORM_SUBMISSION_STATUS";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SHOW_DASHBOARD = "SHOW_DASHBOARD";


export {
    FORM_SUBMISSION_STATUS,
    LOGIN,
    LOGOUT,
    SHOW_DASHBOARD
}